### ISSUE TITLE
在Linux上部署0.9pre1出错

### ISSUE THREAD

**Issue by ConstasJ** [SakuraLLM/Sakura-13B-Galgame#11]
![image](https://github.com/SakuraLLM/Sakura-13B-Galgame/assets/61967203/1b467483-37ec-4916-9358-8595e0d71c97)
如图

**Comment by pipixia244** [comment]
llama-cpp-python还没有支持0.9的底模qwen，目前可以编译[llama.cpp](https://github.com/ggerganov/llama.cpp)使用。另外，0.9目前仍为测试版本，仍可能存在质量问题。如正式使用请使用0.8版本模型，支持更全面。
