### ISSUE TITLE
translate_title貌似是必选的, 但是README里只是在注释里提了一下

### ISSUE THREAD

**Issue by miku1958** [SakuraLLM/Sakura-13B-Galgame#18]
Start translating...
Traceback (most recent call last):
  File "/Volumes/GPT/Sakura-13B-Galgame/translate_epub.py", line 270, in <module>
    main()
  File "/Volumes/GPT/Sakura-13B-Galgame/translate_epub.py", line 172, in main
    if args.translate_title:
AttributeError: 'Namespace' object has no attribute 'translate_title'

**Comment by miku1958** [comment]
加上了的话反而报错了
usage: translate_epub.py [-h] [--listen LISTEN] [--auth AUTH] [--no-auth]
                         [-l {trace,debug,info,warning,error,critical}]
                         [--model_name_or_path MODEL_NAME_OR_PATH] [--use_gptq_model]
                         [--model_version MODEL_VERSION] [--trust_remote_code] [--llama] [--llama_cpp]
                         [--use_gpu] [--n_gpu_layers N_GPU_LAYERS] [--data_path DATA_PATH]
                         [--data_folder DATA_FOLDER] [--output_folder OUTPUT_FOLDER]
                         [--text_length TEXT_LENGTH]
translate_epub.py: error: unrecognized arguments: --translate_title

**Comment by pipixia244** [comment]
因server切换openai api之际未修改完成导致的bug。

可先将此参数删去，马上修复。

**Comment by pipixia244** [comment]
已修复。
