### ISSUE TITLE
关于人名和代词的建议

### ISSUE THREAD

**Issue by miku1958** [SakuraLLM/Sakura-13B-Galgame#23]
我发现如果提前把人名给替换成中文再进行翻译的话, 可以很有效的解决代词的问题, 我是从wiki上把人名和翻译扒下来的再用Calibre提前替换掉的, 效果还行, 但一旦出现wiki里没有的小配角, 它的名字就会变来变去, 只要变得像女性那它的代词就会变成她. 比如:
<img width="1840" alt="image" src="https://github.com/SakuraLLM/Sakura-13B-Galgame/assets/24806909/db586e71-5f26-430e-b8b0-9db974858955">

建议可以加多个参数, 传入一个名词替换列表, 然后用llm翻译前先把这些名词替换掉

**Comment by pipixia244** [comment]
前期替换目前在[轻小说机翻机器人](https://books.fishhawk.top/)中已经支持。可以在该网站编辑“术语表”，网站会在模型翻译文本前先对文本进行替换，将术语表中存在的日语词更换为对应的词。

同时，本地翻译脚本已有计划支持术语表。Server API由于是API属性，所以将不会内置术语表功能，而是由前端进行术语替换后再发送请求。

不过，我觉得这种形式并不能算模型本身的性能提升，只能算是缓解当前存在的问题的trick。如果有能直接提升模型相关能力的办法，欢迎补充~

**Comment by miku1958** [comment]
主要是, 不同的人对同一个名字都会有不同的翻译, 能不能让模型先读一遍整本小说, 然后让它把每个片段里可能出现的人名给提取出来, 然后如果有术语表的话就匹配一下术语表, 让模型先统一把缺失的人名翻译一次作为术语表的补充, 如果没有术语表就相当于让模型去生成术语表了

**Comment by pipixia244** [comment]
后面会考虑做进脚本中，不过目前轻小说机翻机器人网站已经具有[统计片假名的工具](https://books.fishhawk.top/toolbox/katakana)，你可以使用这个工具来统计片假名，然后自行规定一个合理的翻译（或使用模型翻译），并制作术语表。

**Comment by pipixia244** [comment]
Closed it.  Please feel free to reopen this issue if you have some new suggestions.

**Comment by bajian** [comment]
> 主要是, 不同的人对同一个名字都会有不同的翻译, 能不能让模型先读一遍整本小说, 然后让它把每个片段里可能出现的人名给提取出来, 然后如果有术语表的话就匹配一下术语表, 让模型先统一把缺失的人名翻译一次作为术语表的补充, 如果没有术语表就相当于让模型去生成术语表了

> 后面会考虑做进脚本中，不过目前轻小说机翻机器人网站已经具有[统计片假名的工具](https://books.fishhawk.top/toolbox/katakana)，你可以使用这个工具来统计片假名，然后自行规定一个合理的翻译（或使用模型翻译），并制作术语表。

我也认为有必要先全本小说扫描一下，统一一个命名。因为并不是每个使用者都会去使用这个统计工具提取人名/专有名词，看了下[轻小说机翻机器人网站]目前大部分的小说其实也没有术语。而目前确实一个小说的人名在没有术语的情况下，会出现很多不同的命名，比如亚伯，挨贝尔，阿贝尔。。这种缺陷，**我认为算是程序明显有必要优先提升的点，而且实现上也并不困难**。
