### ISSUE TITLE
能不能出一个7b或者6b的模型

### ISSUE THREAD

**Issue by lingyezhixing** [SakuraLLM/Sakura-13B-Galgame#34]
现在主流的8g显存跑Q2都费劲，我知道这是强人所难，但还是希望作者能试一试

**Comment by pipixia244** [comment]
TODO中已有此计划。
https://github.com/SakuraLLM/Sakura-13B-Galgame#todo
问题在于性能的下降上，相比13B的质量必然有所下滑，等我之后测试一下了。
