### ISSUE TITLE
[Bug] 涉及特殊符号和生僻片假名时输出会出现bug

### ISSUE THREAD

**Issue by YamadaKinji** [SakuraLLM/Sakura-13B-Galgame#35]
**Describe the bug**
一旦翻译内容中出现特殊符号，如❤，或是出现生僻片假名，或者出现大量重复的用于表示长音的假名，模型会返回大量重复的某个词汇的翻译结果。

**Comment by pipixia244** [comment]
退化了，尝试设置frequency_penalty为非0值，如0.2。
