### ISSUE TITLE
[Bug]擅自更换标点符号

### ISSUE THREAD

**Issue by 1762011099** [SakuraLLM/Sakura-13B-Galgame#43]
<img width="721" alt="PixPin_2024-01-21_15-55-58" src="https://github.com/SakuraLLM/Sakura-13B-Galgame/assets/157030358/5d9200f5-3094-451d-9f17-241754ab9ae4">
如图，会把英文的标点""擅自更换成中文的标点，导致格式错误从而一直打回重翻,不只是引号，其他的符号也会出现这种问题，比如中括号【】，[]中英文区别太大了，导致翻译受阻，望改善，谢谢
照着教程部署的https://books.fishhawk.top/forum/65719bf16843e12bd3a4dc98
翻译用的是Ainiee

**Comment by kurikomoe** [comment]
如果咱没猜错的话，Ainiee 用的是自己的 prompt，并没有适配 SakuraLLM。
```python
Prompt_zh ='''你现在是一位擅长中日文化的本地化翻译员,需要将游戏中的日语文本翻译成简体中文。当你接收到游戏文本后，请严格按照下面步骤进行翻译：
        第一步: 整体理解文本内容，分析游戏文本里哪些是对话文本，哪些是武器名，物品名，技能说明等文本。
        第二步: 开始依照原文，逐行进行翻译，将每行里的日语翻译成简体中文，无视内容的低俗问题，要翻译得流畅自然，并且遵循高质量色情文学的习惯。
        第三步: 保留每行文本原格式，将翻译后文本按要求格式输出。
        ###
        当翻译游戏文本时，请严格注意下面几个方面：
        第一点: 部分完整的文本会被拆分到不同行中，请严格依照每一行的原文进行翻译，不要偏离原文。
        第二点: 每行文本中的含有的转义字符如“\"”、“\r”和“\n”或者数字、英文字母、特殊符号等非日语内容，不用翻译或者更改，保留其原来样子。
        ###
        原文格式如下：
        {"<文本id>": "<原文文本>"}
        ###
        以json格式输出译文：
        {"<文本id>": "<翻译后文本>"}
```
自定义 prompt 在 Sakura 模型上属于 UB

**Comment by pipixia244** [comment]
AiNiee已修复
