### ISSUE TITLE
[Feature Request] 大佬训练的时候有考虑用DPO或者PPO吗

### ISSUE THREAD

**Issue by pengjianqiang** [SakuraLLM/Sakura-13B-Galgame#44]
**Is your feature request related to a problem? Please describe.**
听说现在DPO训练方法比较稳定，效果更好

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pipixia244** [comment]
已有计划 https://github.com/SakuraLLM/Sakura-13B-Galgame/issues/42 ，但目前数据量不够。
