### ISSUE TITLE
大佬求带，想一起整一波大模型训练

### ISSUE THREAD

**Issue by pengjianqiang** [SakuraLLM/Sakura-13B-Galgame#46]
大佬求带，想一起整一波大模型训练，为日翻中添砖加瓦

**Comment by pengjianqiang** [comment]
提供8张V100支持

**Comment by pipixia244** [comment]
不好意思，因为模型使用的数据集不会公开，所以不会考虑在模型训练上进行扩展。

**Comment by pipixia244** [comment]
如果你想训练ACG领域内的其他类型模型（如角色扮演，文章续写等），我们也提供了只经过领域内数据预训练的[Sakura-13B-Base](https://huggingface.co/SakuraLLM/Sakura-13B-Base-v0.9.0)模型。
