### ISSUE TITLE
软件无法调用SakuraAPI

### ISSUE THREAD

**Issue by oldtian123** [SakuraLLM/Sakura-13B-Galgame#47]
使用AiNiee调用V0.9模型，提示错误代码503
使用Sakura工作区调用网页提示404报错
搭建方式按照Wiki中的Python搭建方式搭建
端口为默认端口，使用纯CPU运行

**Comment by oldtian123** [comment]
不知道与这个有没有关系 
__main__[34160] WARNING Auth is disabled!
pydantic\_internal\_fields.py:149: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
pydantic\_internal\_fields.py:149: UserWarning: Field "model_version" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
pydantic\_internal\_fields.py:149: UserWarning: Field "model_quant" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
pydantic\_internal\_fields.py:149: UserWarning: Field "model_name_or_path" has conflict with protected namespace "model_".

**Comment by pipixia244** [comment]
请提供SakuraAPI和对应翻译工具的完整命令行log~

**Comment by oldtian123** [comment]
2024-02-14 16:36:19 山之仙智升 __main__[40056] WARNING Auth is disabled!
pydantic\_internal\_fields.py:149: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
pydantic\_internal\_fields.py:149: UserWarning: Field "model_version" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
pydantic\_internal\_fields.py:149: UserWarning: Field "model_quant" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
pydantic\_internal\_fields.py:149: UserWarning: Field "model_name_or_path" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
2024-02-14 16:36:19 山之仙智升 __main__[40056] INFO Current server config: Server(listen: 127.0.0.1:5000, auth: None:None)
2024-02-14 16:36:19 山之仙智升 __main__[40056] INFO Current model config: SakuraModelConfig(model_name_or_path='sakura-13b-lnovel-v0.9b-Q4_K_M.gguf', use_gptq_model=False, use_awq_model=False, trust_remote_code=True, text_length=512, llama=False, llama_cpp=True, use_gpu=False, n_gpu_layers=0, vllm=False, enforce_eager=False, tensor_parallel_size=1, gpu_memory_utilization=0.9, model_name=None, model_quant=None, model_version='0.9')
bin C:\Users\28047\Downloads\Compressed\SakuraAPI-b158-win-cu121-x64\_internal\bitsandbytes\libbitsandbytes_cuda121.dll
2024-02-14 16:36:21 山之仙智升 utils.model[40056] INFO loading model ...
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   yes
ggml_init_cublas: CUDA_USE_TENSOR_CORES: no
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3070, compute capability 8.6, VMM: yes
llama_model_loader: loaded meta data with 19 key-value pairs and 323 tensors from sakura-13b-lnovel-v0.9b-Q4_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = qwen
llama_model_loader: - kv   1:                               general.name str              = Qwen
llama_model_loader: - kv   2:                        qwen.context_length u32              = 8192
llama_model_loader: - kv   3:                           qwen.block_count u32              = 40
llama_model_loader: - kv   4:                      qwen.embedding_length u32              = 5120
llama_model_loader: - kv   5:                   qwen.feed_forward_length u32              = 27392
llama_model_loader: - kv   6:                        qwen.rope.freq_base f32              = 10000.000000
llama_model_loader: - kv   7:                  qwen.rope.dimension_count u32              = 128
llama_model_loader: - kv   8:                  qwen.attention.head_count u32              = 40
llama_model_loader: - kv   9:      qwen.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  10:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  11:                      tokenizer.ggml.tokens arr[str,152064]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  12:                  tokenizer.ggml.token_type arr[i32,152064]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  13:                      tokenizer.ggml.merges arr[str,151387]  = ["臓 臓", "臓臓 臓臓", "i n", "臓 t",...
llama_model_loader: - kv  14:                tokenizer.ggml.bos_token_id u32              = 151644
llama_model_loader: - kv  15:                tokenizer.ggml.eos_token_id u32              = 151645
llama_model_loader: - kv  16:            tokenizer.ggml.unknown_token_id u32              = 151643
llama_model_loader: - kv  17:               general.quantization_version u32              = 2
llama_model_loader: - kv  18:                          general.file_type u32              = 15
llama_model_loader: - type  f32:  121 tensors
llama_model_loader: - type q5_0:   20 tensors
llama_model_loader: - type q8_0:   20 tensors
llama_model_loader: - type q4_K:  121 tensors
llama_model_loader: - type q5_K:   40 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens definition check successful ( 421/152064 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = qwen
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 152064
llm_load_print_meta: n_merges         = 151387
llm_load_print_meta: n_ctx_train      = 8192
llm_load_print_meta: n_embd           = 5120
llm_load_print_meta: n_head           = 40
llm_load_print_meta: n_head_kv        = 40
llm_load_print_meta: n_layer          = 40
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 27392
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 8192
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 13B
llm_load_print_meta: model ftype      = Q4_K - Medium
llm_load_print_meta: model params     = 14.17 B
llm_load_print_meta: model size       = 8.79 GiB (5.33 BPW)
llm_load_print_meta: general.name     = Qwen
llm_load_print_meta: BOS token        = 151644 '<|im_start|>'
llm_load_print_meta: EOS token        = 151645 '<|im_end|>'
llm_load_print_meta: UNK token        = 151643 '<|endoftext|>'
llm_load_print_meta: LF token         = 30 '?'
llm_load_tensors: ggml ctx size       =    0.12 MiB
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: system memory used  = 9005.79 MiB
llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/41 layers to GPU
..........................................................................................
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_new_context_with_model: KV self size  = 1600.00 MiB, K (f16):  800.00 MiB, V (f16):  800.00 MiB
llama_build_graph: non-view tensors processed: 924/924
llama_new_context_with_model: compute buffer total size = 310.19 MiB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 |

llama_print_timings:        load time =    5934.21 ms
llama_print_timings:      sample time =       0.83 ms /    14 runs   (    0.06 ms per token, 16949.15 tokens per second)
llama_print_timings: prompt eval time =    5934.15 ms /    77 tokens (   77.07 ms per token,    12.98 tokens per second)
llama_print_timings:        eval time =    6089.78 ms /    13 runs   (  468.44 ms per token,     2.13 tokens per second)
llama_print_timings:       total time =   12113.99 ms
{'choices': [{'finish_reason': 'stop',
              'index': 0,
              'logprobs': None,
              'text': 'GDP，y差为上天， table@n.'}],
 'created': 1707899783,
 'id': 'cmpl-09ccca9a-e280-4998-ad65-b8b0a5ab58be',
 'model': 'sakura-13b-lnovel-v0.9b-Q4_K_M.gguf',
 'object': 'text_completion',
 'usage': {'completion_tokens': 13, 'prompt_tokens': 77, 'total_tokens': 90}}
2024-02-14 16:36:36 山之仙智升 root[40056] WARNING model output is not correct, please check the loaded model
2024-02-14 16:36:36 山之仙智升 root[40056] WARNING input: <|im_start|>system
你是一个轻小说翻译模型，可以流畅通顺地以日本轻小说的风格将日文翻译成简体中文，并联系上下文正确使用人称代词，不擅自添加原文中没有的代词。<|im_end|>
<|im_start|>user
将下面的日文文本翻译成中文：やる気マンゴスキン<|im_end|>
<|im_start|>assistant

2024-02-14 16:36:36 山之仙智升 root[40056] WARNING ground_truth: 干劲Mangoskin
2024-02-14 16:36:36 山之仙智升 root[40056] WARNING current output: prompt_token=77 new_token=13 text='GDP，y差为上天， table@n.' finish_reason='stop'
2024-02-14 16:36:36 山之仙智升 __main__[40056] INFO Server will run at http://127.0.0.1:5000, preparing...
[2024-02-14 16:36:36 +0800] [40056] [INFO] Running on http://127.0.0.1:5000 (CTRL + C to quit)
2024-02-14 16:36:36 山之仙智升 hypercorn.error[40056] INFO Running on http://127.0.0.1:5000 (CTRL + C to quit)

**Comment by oldtian123** [comment]
以上是完整的命令行log

**Comment by laognf95** [comment]
似乎是轻小说机翻机器人网站换了api，原本教程中是输入http://127.0.0.1:5000/api/v1/generate这个链接，现在变成指定主机自动调用api了，如果在添加翻译器的时候启用了Llama Api，他的filename是“/completion”，并且在源代码中的确没有找到这个；不启用的话会显示一个旧版，然后filename是“/v1/chat/completions”，或许是这个问题。。 

我在改了这个之后遇到了其他的问题，似乎是firefox拦了我的请求，提示的错误是
已阻止加载混合活动内容“http://192.168.1.3:5000/v1/chat/completions”
把浏览器的security.mixed_content.block_active_content选项设置成false之后，提示的错误是
已拦截跨源请求：同源策略禁止读取位于 http://192.168.1.3:5000/v1/chat/completions 的远程资源。（原因：CORS 头缺少 'Access-Control-Allow-Origin'）。状态码：502。
已拦截跨源请求：同源策略禁止读取位于 http://192.168.1.3:5000/v1/chat/completions 的远程资源。（原因：CORS 请求未能成功）。状态码：(null)。

按照教程直接翻译文本文件成功了，根据\tests里的例子和运行日志里的测试的prompt用python的requests向http://192.168.1.3:5000/api/v1/generate丢post也成功翻译出来了。。 但是轻小说机翻机器人还是用不起来。。
希望有路过大佬能救一下。。

**Comment by kurikomoe** [comment]
> 似乎是轻小说机翻机器人网站换了api，原本教程中是输入 http://127.0.0.1:5000/api/v1/generate 这个链接，现在变成指定主机自动调用api了，如果在添加翻译器的时候启用了Llama Api，他的filename是“/completion”，并且在源代码中的确没有找到这个（只有一个/completions）；不启用的话会显示一个旧版，然后filename是“/v1/chat/completions”，或许是这个问题。。
> 
> 我在改了这个之后遇到了其他的问题，似乎是firefox拦了我的请求，提示的错误是 已阻止加载混合活动内容“[http://192.168.1.3:5000/v1/chat/completions”](http://192.168.1.3:5000/v1/chat/completions%E2%80%9D) 把浏览器的security.mixed_content.block_active_content选项设置成false之后，提示的错误是 已拦截跨源请求：同源策略禁止读取位于 http://192.168.1.3:5000/v1/chat/completions 的远程资源。（原因：CORS 头缺少 'Access-Control-Allow-Origin'）。状态码：502。 已拦截跨源请求：同源策略禁止读取位于 http://192.168.1.3:5000/v1/chat/completions 的远程资源。（原因：CORS 请求未能成功）。状态码：(null)。
> 
> 按照教程直接翻译文本文件成功了，根据\tests里的例子和运行日志里的测试的prompt用python的requests向 http://192.168.1.3:5000/api/v1/generate 丢post也成功翻译出来了。。 但是轻小说机翻机器人还是用不起来。。 希望有路过大佬能救一下。。

可以先用 chrome 系的浏览器，Firefox 的同源策略之前似乎有点问题，咱回实验室后看一下。
轻小说机翻站上使用建议用 [llama.cpp](https://github.com/ggerganov/llama.cpphttps://github.com/ggerganov/llama.cpp)，机翻站会校验模型指纹，旧版之后不一定还会支持。具体使用教程见机翻站站内教程。

**Comment by kurikomoe** [comment]
> 似乎是轻小说机翻机器人网站换了api，原本教程中是输入 http://127.0.0.1:5000/api/v1/generate 这个链接，现在变成指定主机自动调用api了，如果在添加翻译器的时候启用了Llama Api，他的filename是“/completion”，并且在源代码中的确没有找到这个（只有一个/completions）；不启用的话会显示一个旧版，然后filename是“/v1/chat/completions”，或许是这个问题。。
> 
> 我在改了这个之后遇到了其他的问题，似乎是firefox拦了我的请求，提示的错误是 已阻止加载混合活动内容“[http://192.168.1.3:5000/v1/chat/completions”](http://192.168.1.3:5000/v1/chat/completions%E2%80%9D) 把浏览器的security.mixed_content.block_active_content选项设置成false之后，提示的错误是 已拦截跨源请求：同源策略禁止读取位于 http://192.168.1.3:5000/v1/chat/completions 的远程资源。（原因：CORS 头缺少 'Access-Control-Allow-Origin'）。状态码：502。 已拦截跨源请求：同源策略禁止读取位于 http://192.168.1.3:5000/v1/chat/completions 的远程资源。（原因：CORS 请求未能成功）。状态码：(null)。
> 
> 按照教程直接翻译文本文件成功了，根据\tests里的例子和运行日志里的测试的prompt用python的requests向 http://192.168.1.3:5000/api/v1/generate 丢post也成功翻译出来了。。 但是轻小说机翻机器人还是用不起来。。 希望有路过大佬能救一下。。

有几个问题：
1. 机翻站已经禁止旧版本 0.8 上传了，所以那个旧版基本上已经被废弃了。
2. 机翻站要求 server 可以上报模型指纹，目前这个功能还在 TODO list 里面。只有 llama.cpp 那边支持这个功能。

所以，机翻站目前直接用 llama.cpp 这个跑叭。

cors 这个问题咱没有复现，看了一下 0.8 的 cors 都是正确设置的。

**Comment by kurikomoe** [comment]
试了一下，CORS 的设置看起来没问题，我这边 Firefox 是能正常使用的。
```shell
python server.py --listen 0.0.0.0:5000 --trust_remote_code \
    --model_name_or_path sakura-13b-lnovel-v0.9b-Q2_K.gguf  \
    --model_version 0.9 --no-auth --log debug --llama_cpp --use_gpu
```

```plain
access-control-allow-methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT
access-control-max-age: 600
access-control-allow-credentials: true
access-control-allow-origin: https://books.fishhawk.top
access-control-allow-headers: authorization,content-type
```

你能提供一下出错的时候，浏览器的访问请求么（F12 开发者工具里面）

**Comment by kurikomoe** [comment]
lack of information.
