### ISSUE TITLE
[Bug]  

### ISSUE THREAD

**Issue by Zhangjiawei2000** [SakuraLLM/Sakura-13B-Galgame#48]
用4080笔记本 运行{启动Sakura服务器-显卡.bat}时出现这种错误cublas11 和cublas12 都试过了

CUDA error: out of memory
  current device: 0, in function ggml_cuda_pool_malloc_vmm at D:\a\llama.cpp\llama.cpp\ggml-cuda.cu:7830
  cuMemSetAccess(g_cuda_pool_addr[device] + g_cuda_pool_size[device], reserve_size, &access, 1)
GGML_ASSERT: D:\a\llama.cpp\llama.cpp\ggml-cuda.cu:241: !"CUDA error"

**Comment by Zhangjiawei2000** [comment]
模型名称：sakura-13b-lnovel-v0.9b-Q4_K_M
模型路径：D:\Desktop\AI\sakura-launcher-cublas12-b2062\sakura-13b-lnovel-v0.9b-Q4_K_M.gguf

准备启动Sakura服务器...

D:\Desktop\AI\sakura-launcher-cublas12-b2062>.\llama\server.exe -m .\sakura-13b-lnovel-v0.9b-Q4_K_M.gguf -c 2048 -ngl 999 -a sakura-13b-lnovel-v0.9b-Q4_K_M --host 127.0.0.1
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4080 Laptop GPU, compute capability 8.9, VMM: yes
{"timestamp":1708614138,"level":"INFO","function":"main","line":2428,"message":"build info","build":2062,"commit":"4833ac20"}
{"timestamp":1708614138,"level":"INFO","function":"main","line":2435,"message":"system info","n_threads":16,"n_threads_batch":-1,"total_threads":32,"system_info":"AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 | "}

llama server listening at http://127.0.0.1:8080

{"timestamp":1708614138,"level":"INFO","function":"main","line":2534,"message":"HTTP server listening","hostname":"127.0.0.1","port":"8080"}
llama_model_loader: loaded meta data with 19 key-value pairs and 323 tensors from .\sakura-13b-lnovel-v0.9b-Q4_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = qwen
llama_model_loader: - kv   1:                               general.name str              = Qwen
llama_model_loader: - kv   2:                        qwen.context_length u32              = 8192
llama_model_loader: - kv   3:                           qwen.block_count u32              = 40
llama_model_loader: - kv   4:                      qwen.embedding_length u32              = 5120
llama_model_loader: - kv   5:                   qwen.feed_forward_length u32              = 27392
llama_model_loader: - kv   6:                        qwen.rope.freq_base f32              = 10000.000000
llama_model_loader: - kv   7:                  qwen.rope.dimension_count u32              = 128
llama_model_loader: - kv   8:                  qwen.attention.head_count u32              = 40
llama_model_loader: - kv   9:      qwen.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  10:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  11:                      tokenizer.ggml.tokens arr[str,152064]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  12:                  tokenizer.ggml.token_type arr[i32,152064]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  13:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  14:                tokenizer.ggml.bos_token_id u32              = 151644
llama_model_loader: - kv  15:                tokenizer.ggml.eos_token_id u32              = 151645
llama_model_loader: - kv  16:            tokenizer.ggml.unknown_token_id u32              = 151643
llama_model_loader: - kv  17:               general.quantization_version u32              = 2
llama_model_loader: - kv  18:                          general.file_type u32              = 15
llama_model_loader: - type  f32:  121 tensors
llama_model_loader: - type q5_0:   20 tensors
llama_model_loader: - type q8_0:   20 tensors
llama_model_loader: - type q4_K:  121 tensors
llama_model_loader: - type q5_K:   40 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens definition check successful ( 421/152064 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = qwen
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 152064
llm_load_print_meta: n_merges         = 151387
llm_load_print_meta: n_ctx_train      = 8192
llm_load_print_meta: n_embd           = 5120
llm_load_print_meta: n_head           = 40
llm_load_print_meta: n_head_kv        = 40
llm_load_print_meta: n_layer          = 40
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: n_embd_k_gqa     = 5120
llm_load_print_meta: n_embd_v_gqa     = 5120
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 27392
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 8192
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 13B
llm_load_print_meta: model ftype      = Q4_K - Medium
llm_load_print_meta: model params     = 14.17 B
llm_load_print_meta: model size       = 8.79 GiB (5.33 BPW)
llm_load_print_meta: general.name     = Qwen
llm_load_print_meta: BOS token        = 151644 '<|im_start|>'
llm_load_print_meta: EOS token        = 151645 '<|im_end|>'
llm_load_print_meta: UNK token        = 151643 '<|endoftext|>'
llm_load_print_meta: LF token         = 30 '?'
llm_load_tensors: ggml ctx size =    0.25 MiB
llm_load_tensors: offloading 40 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 41/41 layers to GPU
llm_load_tensors:        CPU buffer size =   417.66 MiB
llm_load_tensors:      CUDA0 buffer size =  8588.02 MiB
...........................................................................................
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:      CUDA0 KV buffer size =  1600.00 MiB
llama_new_context_with_model: KV self size  = 1600.00 MiB, K (f16):  800.00 MiB, V (f16):  800.00 MiB
llama_new_context_with_model:  CUDA_Host input buffer size   =    14.01 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =   337.70 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =    11.00 MiB
llama_new_context_with_model: graph splits (measure): 3
Available slots:
 -> Slot 0 - max context: 2048
{"timestamp":1708614142,"level":"INFO","function":"main","line":2555,"message":"model loaded"}
all slots are idle and system prompt is empty, clear the KV cache
{"timestamp":1708614148,"level":"INFO","function":"log_server_request","line":2375,"message":"request","remote_addr":"127.0.0.1","remote_port":11327,"status":200,"method":"GET","path":"/","params":{}}
{"timestamp":1708614148,"level":"INFO","function":"log_server_request","line":2375,"message":"request","remote_addr":"127.0.0.1","remote_port":11328,"status":200,"method":"GET","path":"/completion.js","params":{}}
{"timestamp":1708614148,"level":"INFO","function":"log_server_request","line":2375,"message":"request","remote_addr":"127.0.0.1","remote_port":11329,"status":200,"method":"GET","path":"/json-schema-to-grammar.mjs","params":{}}
{"timestamp":1708614148,"level":"INFO","function":"log_server_request","line":2375,"message":"request","remote_addr":"127.0.0.1","remote_port":11327,"status":200,"method":"GET","path":"/index.js","params":{}}
slot 0 is processing [task id: 0]
slot 0 : in cache: 0 tokens | to process: 49 tokens
slot 0 : kv cache rm - [0, end)
CUDA error: out of memory
  current device: 0, in function ggml_cuda_pool_malloc_vmm at D:\a\llama.cpp\llama.cpp\ggml-cuda.cu:7830
  cuMemSetAccess(g_cuda_pool_addr[device] + g_cuda_pool_size[device], reserve_size, &access, 1)
GGML_ASSERT: D:\a\llama.cpp\llama.cpp\ggml-cuda.cu:241: !"CUDA error"

**Comment by pipixia244** [comment]
问题在于`CUDA error: out of memory`，显存不够。解决办法要么offload到cpu，要么换更高显存的显卡，要么换更小的模型。

**Comment by starP-W** [comment]
```
D:\Desktop\AI\sakura-launcher-cublas12-b2062>.\llama\server.exe -m .\sakura-13b-lnovel-v0.9b-Q4_K_M.gguf -c 2048 -ngl 999 -a sakura-13b-lnovel-v0.9b-Q4_K_M --host 127.0.0.1
```
12G显存不足以完整跑起使用llama.cpp加载的sakura模型，把```-c```参数后面的2048调整到1024或者512试试
但以我自己的经验来看，llama.cpp有时候会出现```slot context shift```的提示并卡在某一句，消耗时间非常长而且翻译也不对。溜了一圈那边的评论区，也有人提出同样的问题但似乎没有很好的解决办法。
个人目前使用的是python部署，没有上述的问题而且默认配置即可加载模型
