### ISSUE TITLE
关于dev_server的几个问题

### ISSUE THREAD

**Issue by pipixia244** [SakuraLLM/Sakura-13B-Galgame#5]
- 此处需将float去掉.
https://github.com/SakuraLLM/Sakura-13B-Galgame/blob/6d48843fe8e495132cc862ec6f390aa3ce9c4f88/api/legacy/type.py#L27

- `GenerateRequest`类里的参数最好只留`['prompt', 'max_new_tokens', 'do_sample', 'temperature', 'top_p', 'repetition_penalty', 'num_beams', 'top_k', 'seed']`这几个，其余的参数可以让使用者在请求中自行添加(`**kwargs`).
https://github.com/SakuraLLM/Sakura-13B-Galgame/blob/6d48843fe8e495132cc862ec6f390aa3ce9c4f88/api/legacy/type.py#L6-L45

- 此处测试模型输出时，如果需要字符串完全相等，不仅需要参数一致，还需要do_sample设置为False，否则会按概率分布随机sample，导致结果不唯一.
https://github.com/SakuraLLM/Sakura-13B-Galgame/blob/6d48843fe8e495132cc862ec6f390aa3ce9c4f88/utils/model.py#L109-L113
https://github.com/SakuraLLM/Sakura-13B-Galgame/blob/6d48843fe8e495132cc862ec6f390aa3ce9c4f88/utils/__init__.py#L3-L19

**Comment by kurikomoe** [comment]
Check the latest commit on dev_server branch
