### ISSUE TITLE
[Bug] 仓库脚本提供的API在多轮对话翻译时存在问题

### ISSUE THREAD

**Issue by kunger97** [SakuraLLM/Sakura-13B-Galgame#52]
**描述一下Bug**
之前曾在TG群组中提过，今天进行了详细的测试，我认为此问题可能是一个BUG。
0.9版本模型支持Chat式的多轮对话，实际使用时仅llama-cpp-python加载的模型支持多轮对话，transformers加载的模型多轮对话会出现问题。
在测试过程中，使用仓库脚本和[QWEN仓库中的openai like api脚本](https://github.com/QwenLM/Qwen/blob/main/openai_api.py)进行测试，均加载SakuraLLM/Sakura-13B-LNovel-v0.9的模型，qwen仓库提供的api脚本多轮对话可以正常返回

**复现步骤**
使用transformers加载SakuraLLM/Sakura-13B-LNovel-v0.9模型，并使用openai形式的API参数进行多轮对话（第二轮就可以复现问题）

**预期结果**
像qwen仓库中的openai like api一样正常进行多轮对话

**截图**

**使用仓库脚本生成，第二轮未能返回正确的翻译结果**
![image](https://github.com/SakuraLLM/Sakura-13B-Galgame/assets/1808555/9871e138-16ad-4d65-99cb-e1f0c5d588eb)
**使用QWEN仓库中的脚本生成，第二轮能返回正确的翻译结果**
![image](https://github.com/SakuraLLM/Sakura-13B-Galgame/assets/1808555/297c93eb-f80a-460a-ad01-14347d658d6a)

**版本与参数（重要）**
 - OS [Ubuntu 20.04.6]
 - Python版本 [3.10]
 - 是否使用GPU，使用什么GPU. [均使用CPU推理]
 - 你使用的llama.cpp/llama-cpp-python/autogptq/transformers库的版本 [transformers==4.33.2]
 - 你使用的模型版本 [SakuraLLM/Sakura-13B-LNovel-v0.9]
 - 如果是模型输出问题，请同时附上模型的解码参数 [参数为仓库中的推荐参数]

**其他信息**

1. 使用仓库中脚本加载模型，进行测试请求的JSON数据

请求时的对话内容
````
[
   {
      "role":"system",
      "content":"你是一个轻小说翻译模型，可以流畅通顺地以日本轻小说的风格将日文翻译成简体中文，并联系上下文 正确使用人称代词，不擅自添加原文中没有的代词。"
   },
   {
      "role":"user",
      "content":"将下面的日文文本翻译成中文：その女――雪那（ゆ きな）・グレイスの\n行動はあまりにも唐突だった。"
   },
   {
      "role":"assistant",
      "content":"那个女人——雪那（yukina）・葛雷斯。\n她的行动太过突然了。"
   },
   {
      "role":"user",
      "content":"将下面的日文文本翻译成中文：グレイスとは恋人でも何でもない。\n仲間ですら ない。"
   }
]
````

返回的结果

````
{
   "choices":[
      {
         "finish_reason":"stop",
         "index":0,
         "message":{
            "content":"那个女人——雪那（yukina）・葛雷斯。\n她的行动太过突然了。\n<|im_start|>user\n将下面的日文文本翻译成中文：グレイスとは恋人でも何でもない。\n仲間ですらない。\n",
            "role":"assistant"
         }
      }
   ],
   "created":1709190448,
   "id":"114514",
   "model":"Sakura-13B-LNovel-0.9-",
   "object":"chat.completion",
   "usage":{
      "completion_tokens":16,
      "prompt_tokens":147,
      "total_tokens":163
   }
}
````

2. 使用QWEN仓库中的脚本加载模型，并进行测试请求的JSON数据

请求时的对话内容

````
[
   {
      "role":"system",
      "content":"你是一个轻小说翻译模型，可以流畅通顺地以日本轻小说的风格将日文翻译成简体中文，并联系上下文 正确使用人称代词，不擅自添加原文中没有的代词。"
   },
   {
      "role":"user",
      "content":"将下面的日文文本翻译成中文：その女――雪那（ゆ きな）・グレイスの\n行動はあまりにも唐突だった。"
   },
   {
      "role":"assistant",
      "content":"那个女人——雪那（yukina）・葛雷斯。\n她的行动太过突然了。"
   },
   {
      "role":"user",
      "content":"将下面的日文文本翻译成中文：グレイスとは恋人でも何でもない。\n仲間ですら ない。"
   }
]
````

返回的结果

````
{
   "model":"sukinishiro",
   "object":"chat.completion",
   "choices":[
      {
         "index":0,
         "message":{
            "role":"assistant",
            "content":"古蕾丝 跟伤无根本不是什么情侣。\n连同伴都不是。",
            "function_call":null
         },
         "finish_reason":"stop"
      }
   ],
   "created":1709190820
}
````

**Comment by kurikomoe** [comment]
0.9 transformer 的模型太大下不动。 @pipixia244  你来叭

**Comment by kunger97** [comment]
修改后可以了。thanks
