### ISSUE TITLE
[Bug] 提供的llama无法加载sakura-13b-qwen2beta-v0.10pre0-IQ4_XS.gguf模型

### ISSUE THREAD

**Issue by HIllya51** [SakuraLLM/Sakura-13B-Galgame#58]
<img width="833" alt="屏幕截图 2024-03-11 141440" src="https://github.com/SakuraLLM/Sakura-13B-Galgame/assets/101191390/603c0aeb-96a4-4159-9443-696870d3b22d">

但是去llama.cpp下载最新版的就可以了。（可能程序版本太旧了不支持新的模型？更新一下OD里提供的程序）

**Comment by pipixia244** [comment]
是的，提供的程序版本没有更新，qwen2结构在很新的版本才支持。

同时，v0.10版本目前仍属于非常pre的测试版，只能当成功能展示来用，并且可能存在一定的质量问题，所以一般会在质量较为理想且稳定的时候再更新对v0.10版本的支持。
