### ISSUE TITLE
[Feature Request]13b跑起来有点慢而且吃力，7b又效果有点差，有没有可能出个10b

### ISSUE THREAD

**Issue by lasxmidnight78** [SakuraLLM/Sakura-13B-Galgame#61]
我测试了一小段翻译，13bq4的速度是7b的一半，而且35层都容易炸显存。7b翻译出明显差异的地方不少，7b还有的跟原文完全不同意思的句子。13bq3只比q4快了10%不到。如果能折中出个10B左右的效果会不会比较适合低配12G的游戏卡。

**Comment by pipixia244** [comment]
yi-9b可能符合你的需求，后续会出yi系列底模的模型。
