### ISSUE TITLE
OpenAI方式调用总是返回stop

### ISSUE THREAD

**Issue by thissensen** [SakuraLLM/Sakura-13B-Galgame#65]
**描述一下Bug**
使用OpenAI调用，FinishReason一直返回stop

**复现步骤**
一开始常规调用是可以的，然后我使用OpenAI的func调用，使其以指定Json格式(JSON Schema)返回内容，出现此错误(该方法经过正规OpenAI验证可用)，当我再切换回常规调用时就一直失败，尝试过删除文件夹目录无效果

**输出内容**
`
{"built_in":true,"chat_example":"<|im_start|>system\nYou are a helpful assistant<|im_end|>\n<|im_start|>user\nHello<|im_end|>\n<|im_start|>assistant\nHi there<|im_end|>\n<|im_start|>user\nHow are you?<|im_end|>\n<|im_start|>assistant\n","function":"main","level":"INFO","line":2878,"msg":"chat template","tid":"6472","timestamp":1711809033}
{"function":"main","hostname":"127.0.0.1","level":"INFO","line":3496,"msg":"HTTP server listening","n_threads_http":"23","port":"8080","tid":"6472","timestamp":1711809033}
{"function":"update_slots","level":"INFO","line":1655,"msg":"all slots are idle","tid":"6472","timestamp":1711809033}
{"function":"launch_slot_with_task","id_slot":0,"id_task":0,"level":"INFO","line":1015,"msg":"slot is processing task","tid":"6472","timestamp":1711809037}
{"function":"update_slots","id_slot":0,"id_task":0,"level":"INFO","line":1939,"msg":"kv cache rm [p0, end)","p0":0,"tid":"6472","timestamp":1711809037}
{"function":"print_timings","id_slot":0,"id_task":0,"level":"INFO","line":313,"msg":"prompt eval time     =     479.40 ms /   696 tokens (    0.69 ms per token,  1451.80 tokens per second)","n_prompt_tokens_processed":696,"n_tokens_second":1451.7996266204984,"t_prompt_processing":479.405,"t_token":0.6888002873563218,"tid":"6472","timestamp":1711809042}
{"function":"print_timings","id_slot":0,"id_task":0,"level":"INFO","line":329,"msg":"generation eval time =    4301.23 ms /   282 runs   (   15.25 ms per token,    65.56 tokens per second)","n_decoded":282,"n_tokens_second":65.56261089845886,"t_token":15.252595744680852,"t_token_generation":4301.232,"tid":"6472","timestamp":1711809042}
{"function":"print_timings","id_slot":0,"id_task":0,"level":"INFO","line":339,"msg":"          total time =    4780.64 ms","t_prompt_processing":479.405,"t_token_generation":4301.232,"t_total":4780.637,"tid":"6472","timestamp":1711809042}
{"function":"update_slots","id_slot":0,"id_task":0,"level":"INFO","line":1637,"msg":"slot released","n_cache_tokens":0,"n_ctx":2048,"n_past":977,"n_system_tokens":0,"tid":"6472","timestamp":1711809042,"truncated":false}
{"function":"log_server_request","level":"INFO","line":2707,"method":"POST","msg":"request","params":{},"path":"/v1/chat/completions","remote_addr":"127.0.0.1","remote_port":10053,"status":200,"tid":"16876","timestamp":1711809042}
{"function":"update_slots","level":"INFO","line":1655,"msg":"all slots are idle","tid":"6472","timestamp":1711809042}
`
![错误截图](https://github.com/SakuraLLM/Sakura-13B-Galgame/assets/43516619/147ed9e8-71ff-4296-9c0a-ecf26cee1e78)

**版本与参数（重要）**
 - OS: windows10 专业版 22H2
 - 版本:llama.cpp
 - GPU：3080 10G
 - 模型:sakura-13b-lnovel-v0.9b-Q2_K.gguf

**其他信息**
如果可以，我希望Sakura可以完美支持OpanAI的function calling，或者让我手填JSON Schema，使其返回我想要的格式

**Comment by pipixia244** [comment]
1. finish reason是stop不是正常现象吗，要么stop（正常输出eos结束）要么length（输出达到预设最大长度结束）
2. 我怎么没看出来上面的图片里哪里报错了
3. 不要使用json mode

**Comment by thissensen** [comment]
是不是Message有可能为null啊，我看Message为null，FinishReason为stop，就误以为机翻异常被中止了

**Comment by pipixia244** [comment]
不管是本仓库的SakuraAPI还是llama.cpp都基本遵循了openai api doc中的格式。

api的具体返回格式可以查看[openai api doc](https://platform.openai.com/docs/api-reference/chat/create)
