### ISSUE TITLE
好像偶尔会输出一些无关的东西（无法复现）

### ISSUE THREAD

**Issue by fatecyx** [SakuraLLM/Sakura-13B-Galgame#67]
用的sakura-13b-lnovel-v0.9b-Q4_K_M
第一次：
很奇怪的输出了：（注：日文中的「○」与「纯」同音）
而且这俩似乎也不同音
"うむうむ、シャルロットちゃんごくろーさまー。\nこーんな上玉エルフをゲットしてくれるなんて、\nルリエルちゃん嬉しいよー。\n見たとこ１００パーセント純血さんみたいだね？\nめずらしー、めずらしー！\n\nジャコモちゃんも喜ぶよー。\nいやー、シャルロットちゃんはご主人様思いの\nいい奴隷だねー！": "嗯嗯，夏洛特妹妹辛苦了～～\n竟然能抓到这等上等货色的精灵，\n琉艾尔妹妹好开心哦～～\n看起来似乎有百分之○是纯血种呢？\n真稀奇、真稀奇！\n\n（注：日文中的「○」与「纯」同音）\n雅各莫弟弟也会很开心哦～～\n哎呀，夏洛特妹妹真是个为主人着想的好奴隶啊～～",

第二次：
后面这一段已经完全无关了
"ダレスが薄ら笑いを浮かべる中、\nジュリアのオークションは滞りなく\n進んで行った。"
'在达雷斯露出冷笑的同时——\n朱莉亚的拍卖会顺利地进行着。\n「接下来是这个！」\n「这是什么？」\n「这是一颗宝石，名叫『月光石』。」\n「哦？这名字听起来挺不错的嘛。」\n「不过呢，它其实是个赝品。」\n「……啥？」\n达雷斯不禁发出错愕的声音。\n朱莉亚则是继续说道：\n「这个东西是我在路上捡到的，我猜应该是有人不小心掉在路边吧。」\n「你、你在说什么啊？这可是月光石耶！？价值连城的好吗！」\n「嗯，你说得没错。不过呢，它只是个赝品而已。」\n「……啥？」\n达雷斯再次发出错愕的声音。\n朱莉亚则是继续说道：\n「这个东西是我在路上捡到的，我猜应该是有人不小心掉在路边吧。」\n「你、你在说什么啊？这可是月光石耶！？价值连城的好吗！」'

有的时候全角数字也会出错（同样无法复现）
 "１０日……１０日か。\n確かだな？\n\n確かにその程度なら、なんとか\nなりそうな気がしてきたぞ……！"
 "只剩五天了啊。\n真的吗？\n\n如果只是这种程度的话，\n感觉应该能勉强应付过去吧……！"

**Comment by pipixia244** [comment]
lm-studio载入并不在支持范围内，“第二次”出现的无关文本输出可能和未正确使用chatml的prompt模板有关。

关于”注“的问题已经记下，可能系数据集问题，后续会进行检查。

**Comment by fatecyx** [comment]
补充一下，这次发现了不少，kaggle上部署的sakura-13b-lnovel-v0.9b-Q4_K_M

    "敗北エロどこ…ここ…？": "败北情色在哪里……这里……？（注：neta《圣龙皇么么茶》）",
    "触手凌辱って胸キュン？": "触手凌辱会心动？（注：日语中，触手凌辱和心动是谐音）",
    "もやしも買えないのォ！？": "连豆芽菜都买不起！？（注：日语中豆芽菜和钱同音）",
    "俺達はデカ太ももとデカケツに救われていた…？": "我们被大屁股和大屁股拯救了……？（注：日语中屁股和屁股发音相同）",
    "女の子でボク……！？ ボクッ娘…！？": "女孩子，我……！？我女儿……！？（注：日语中我女儿和我同音）",
    "まん？": "真？（注：日语中「真」和「撸」同音）",
    "でんまってデンマークのことでしょうか？": "丹麦是丹麦吗？（注：日语中「丹麦」和「朋友」发音相近）",
    "メティアちゃんどこ…？ ここ…？": "美蒂亚在哪里……？这里……？（注：日语中「美蒂亚」和「午安」的发音很像）",
    "えっと……これは……処刑？": "呃……这是……处刑？（注：此处为日语谐音梗）",
    "ぐしゃって言いましたが？": "我刚才说了什么？（注：日语中“医生”和“咕咚”发音相似）",
    "どみねーたー？": "多米奈特？（注：多米奈特是《神龙之吻》的女主角，也是《神龙之吻2》的主角）",
    "淫紋！ もんもん！！": "淫纹！（注：日语中「纹」和「无」同音）",
    "シコシコ致しました、で満足か？": "撸撸撸撸到满意为止？（注：日语中「喂食」和「撸」同音）",
    "しんぎゅらりてぃ……？": "新鬼畜体……？（注：neta新体操）",
    "感情がないならおっぱいをもにもにしても？": "既然没有感情，那揉胸揉胸又算什么？（注：此处原文为「胸揉胸」，此处为意译）",
    "えぇ……！？": "诶诶……！？（注：此处为日语中的拟声词，表示惊讶）",
    "それを阻止しながら戦えって話？": "要一边阻止那个一边战斗？（注：日语中「一边」和「一边」发音相同）",
    "そんなにあるかなこういう事！？": "这种事情，真的会经常发生吗！？（注：日语中“经常发生”和“不太可能”发音相近）",
    "回復ドリンク製造工場もここに…？": "恢复饮料制造工厂也在这里……？（注：neta《钢之炼金术师》）",
    "紅茶メインで緑茶売ってない？": "主打红茶，没有卖绿茶？（注：此处指日本）",
    "テンタクル？": "触手？（注：日文发音类似）",
    "ええと……水かきとか？": "呃……水陆两栖的？（注：日语中水陆两栖的发音和青蛙很像）",
    "あのフロッグスさんさっきの人は…？": "那位青蛙先生，刚才的人是……？（注：日语中青蛙的发音与刚才的人发音相似）",
    "丸呑みフェチですかぁ！？": "喜欢被生吞吗！？（注：日语中生吞与喜欢被生吞发音相似）",
    "ソフト？ ソフトリョナOK？ ノットダイ？？": "软的？软的OK？不打？？（注：日语中软的与不打发音相似）",
    "やさしい…やさしい？": "温柔……温柔？（注：日语中温柔与不打发音相似）",
    "引退配信いつやるんだっけ？": "引退直播是什么时候？（注：此处为日文）",
    "ぽつーん": "（注：neta出自《名侦探柯南》中，毛利小五郎在解释「爽」这个词时，说成了「教爽」）",
    "広いだけで深みはないですよね？": "只是很宽广，没有深度对吧？（注：日语中「宽广」和「没有深度」发音相近）",
    "ボテ腹メイデンを心待ちにしてるんだが？": "我可是很期待大肚子处女哦？（注：大肚子处女，出自《美少女死神 还我Ｈ之魂！》）",
    "んもむっ……！？": "嗯唔……！？（注：此处为拟声词，下同）",
    "メイデンにこ…": "处女座にこ…（注：nico，nico动画的昵称）",
    "メイデンよゆーね": "处女座よゆーね（注：youtuber，nico动画的昵称）",
    "電マあん？": "按摩棒？（注：日语中「按摩棒」和「被骗」同音）",
    "しりとりしよ？": "来玩接龙吧？（注：日语中接龙的发音与医生同音）",

**Comment by pipixia244** [comment]
新模型应该已经解决此问题。
