### ISSUE TITLE
原文中出现&0字符后，会翻译成大量重复的~

### ISSUE THREAD

**Issue by pxBang** [SakuraLLM/Sakura-13B-Galgame#70]
**描述一下Bug**

原文中出现`&0`字符后，会翻译成大量重复的`~`，导致游戏崩溃

**复现步骤**

原文中添加`&0`即可

**预期结果**

原文中出现`&0`字符后，会翻译成大量重复的`~`，导致游戏崩溃

**截图**

![屏幕截图 2024-04-17 110916](https://github.com/SakuraLLM/Sakura-13B-Galgame/assets/70083218/c46b88f9-b894-4532-91d5-faf86da571ee)

![屏幕截图 2024-04-17 111235](https://github.com/SakuraLLM/Sakura-13B-Galgame/assets/70083218/a78d2120-f13a-435f-9079-65f136822be2)

**版本与参数（重要）**
 - OS: [e.g. Windows]
 - Python版本 [e.g. 3.10]
 - 是否使用GPU，使用什么GPU. [e.g. NVIDIA GeForce 4090]
 - 你使用的llama.cpp/llama-cpp-python/autogptq/transformers库的版本 [e.g. llama.cpp b1604 cu117]
 - 你使用的模型版本 [e.g. Sakura-13B-LNovel-v0.9.0pre3-Q5_K_M.gguf]
 - 如果是模型输出问题，请同时附上模型的解码参数 [e.g. temperature: 0.1, top_p:0.3, frequency_penalty: 0.0]

模型版本：sakura-13b-lnovel-v0.9b-Q2_K.gguf -c 2048 -ngl 999 -a sakura-13b-lnovel-v0.9b-Q2_K --host 127.0.0.1

**其他信息**
关于你遇到的Bug的更多信息

**Comment by pipixia244** [comment]
增加frequency_penalty可解决。
