### ISSUE TITLE
[Bug] 基于qwen1.5的模型都不能运行

### ISSUE THREAD

**Issue by tisapphire** [SakuraLLM/Sakura-13B-Galgame#71]
**描述一下Bug**
在kaggle上部署

`!git clone https://github.com/SakuraLLM/Sakura-13B-Galgame.git
%cd Sakura-13B-Galgame

!pip install llama-cpp-python --prefer-binary --extra-index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/AVX2/cu121
!pip install -q -r requirements.llamacpp.txt
!pip install -q pyngrok`

`ngrokToken = "************************************"
MODEL = "sakura-13b-lnovel-v0.9b-Q6_K"

from huggingface_hub import hf_hub_download
from pathlib import Path

if ngrokToken:
    from pyngrok import conf,ngrok
    conf.get_default().auth_token = ngrokToken
    conf.get_default().monitor_thread = False
    ssh_tunnels = ngrok.get_tunnels(conf.get_default())
    if len(ssh_tunnels) == 0:
        ssh_tunnel = ngrok.connect(5000)
        print('address:' + ssh_tunnel.public_url)
    else:
        print('address:' + ssh_tunnels[0].public_url)
        
MODEL_PATH = f"./models/{MODEL}.gguf"
if not Path(MODEL_PATH).exists():
    hf_hub_download(repo_id="SakuraLLM/Sakura-14B-LNovel-v0.9b-GGUF",filename = f"{MODEL}.gguf", local_dir = "models/")

!python server.py \
    --model_name_or_path $MODEL_PATH \
    --llama_cpp \
    --use_gpu \
    --model_version v0.9 \
    --trust_remote_code \
    --no-auth`

代码如上。在运行基于qwen的0.9模型时正常运行。但换成基于qwen1.5模型的无论是0.9还是0.10pre，都会在中间显示qwen2是unknown，最后"assert self.model is not None"报错结束运行

python 3.10
llama-cpp-python 0.2.26
T4*2

**Comment by pipixia244** [comment]
请截图/文字附上完整的错误log

**Comment by tisapphire** [comment]
![屏幕截图 2024-04-21 150644](https://github.com/SakuraLLM/Sakura-13B-Galgame/assets/85567150/673fc573-d2ab-44fa-98b9-6a7b48911e11)
![屏幕截图 2024-04-21 150952](https://github.com/SakuraLLM/Sakura-13B-Galgame/assets/85567150/acb553fe-9e69-4825-957e-9619ebbc40f2)
![屏幕截图 2024-04-21 151039](https://github.com/SakuraLLM/Sakura-13B-Galgame/assets/85567150/df20c884-af4f-42fc-8fe4-82420f9d539b)
![屏幕截图 2024-04-21 151101](https://github.com/SakuraLLM/Sakura-13B-Galgame/assets/85567150/3db2a9f2-7f95-463e-b432-460a55b689ea)

**Comment by kurikomoe** [comment]
llama.cpp-python v0.2.26 对应的 [llama.cpp @ f679349](https://github.com/ggerganov/llama.cpp/tree/f6793491b5af6da75edad34d6f503ef86d31b09f) 此版本 llama.cpp 还未支持 qwen，请升级 llama.cpp-python 依赖

**Comment by kurikomoe** [comment]
另外，`--model_version v0.9` ，不应该是 `--model_version 0.9` 么。
参见 https://github.com/SakuraLLM/Sakura-13B-Galgame/blob/main/usage.md

**Comment by tisapphire** [comment]
多谢指教
