### ISSUE TITLE
Sakura-14B-LNovel-v0.9b9 is missing

### ISSUE THREAD

**Issue by adsf0427** [SakuraLLM/Sakura-13B-Galgame#73]
I'd like to run  [Sakura-14B-LNovel-v0.9b] model using vllm backend, it seems vllm doesn't suppoert .gguf format. Can u provide hf format of this model like SakuraLLM/Sakura-1B8-Qwen2beta-v0.9 ? Thanks.

**Comment by pipixia244** [comment]
The full hf format of Sakura-14B-LNovel-v0.9b model may use over 28G VRAM, and cannot be loaded on any Geforce/RadeonRX GPUs, so currently it has not been updated to huggingface.

Also we recommend you to use llama.cpp and GGUF format of sakura models, for they are faster in inference and have lower usage in VRAM, but only non-significant loss.

**Comment by kunger97** [comment]
Intel 系显卡的IPEX-LLM推理速度要优于 llama.cpp，并且支持使用全量HF模型进行Int4/Int8量化，希望可以上传一下改HF模型

**Comment by pipixia244** [comment]
[Sakura-14B-LNovel-v0.9b] is now uploaded to HF.

https://huggingface.co/SakuraLLM/Sakura-14B-LNovel-v0.9b
