### ISSUE TITLE
[使用疑問]使用apipost模擬api請求時遇到問題

### ISSUE THREAD

**Issue by Leowolf93** [SakuraLLM/Sakura-13B-Galgame#75]
我按照如下教程進行配置：
https://github.com/SakuraLLM/Sakura-13B-Galgame/wiki/Python%E9%83%A8%E7%BD%B2%E6%95%99%E7%A8%8B

使用“打包好的免Python环境的Sakura API程序包”的方式，下載好了SakuraAPI-b192-win-cu121-x64.zip

同時，我下載了sakura-13b-lnovel-v0.9b-Q5_K_M.gguf模型。

使用如下命令啓動命令行
./server.exe --model_name_or_path sakura-13b-lnovel-v0.9b-Q5_K_M.gguf --trust_remote_code --no-auth --log info --model_version 0.9 --llama_cpp --use_gpu

我打開apipost，想寫一個post請求到http://127.0.0.1:5000/api/v1/generate

但是在post的格式中我找不到如何編寫格式。

自行摸索的格式為：
`{
	"messages": [
		{
			"role": "system",
			"content": "你是一个轻小说翻译模型，可以流畅通顺地以日本轻小说的风格将日文翻译成简体中文，并联系上下文正确使用人称代词，不擅自添加原文中没有的代词。"
		},
		{
			"role": "user",
			"content": "将下面的日文文本翻译成中文：こんにちは"
		}
	],
	"prompt": "你是一个轻小说翻译模型，可以流畅通顺地以日本轻小说的风格将日文翻译成简体中文，并联系上下文正确使用人称代词，不擅自添加原文中没有的代词。",
	"beams number": 1,
	"max_new_tokens": 512,
	"min_new_tokens": 1,
	"do_sample": true,
	"temperature": 0.1,
	"top_p": 0.3,
	"top_k": 40,
	"num_beams": 1,
	"seed": 65535,
	"repetition_penalty": 1
}`
返回值為：
`{
	"results": [
		{
			"new_token": 0,
			"text": ""
		}
	]
}`

十分抱歉，可能是我沒有理解導致的，能否告知一下請求體如何編寫？謝謝！

**Comment by kurikomoe** [comment]
https://github.com/SakuraLLM/Sakura-13B-Galgame/blob/main/tests/example_openai.py

**Comment by Leowolf93** [comment]
> https://github.com/SakuraLLM/Sakura-13B-Galgame/blob/main/tests/example_openai.py

@kurikomoe 
感谢您的回复！
我尝试了一下，这个版本似乎不适合目前最新的0.9模型，而且缺少了一些参数。

**Comment by pipixia244** [comment]
请使用[本仓库内的示例脚本](https://github.com/SakuraLLM/Sakura-13B-Galgame/blob/main/tests/example_openai.py)。

请不要自行使用任何其他交互工具与模型API交互，除非你非常清楚。
