### ISSUE TITLE
请求添加Sakura-14B-Qwen2beta-v0.9-GGUF的IQ3_S量化版本（8G显存的较优选择）

### ISSUE THREAD

**Issue by lingyezhixing** [SakuraLLM/Sakura-13B-Galgame#78]
经过多轮实验，我发现针对14B规模的模型，采用IQ3_S量化方案并配置1500作为上下文窗口大小，能够完美适配当前主流的8GB显存环境（实际运行中稳定占用约7.7GB），同时有较好的翻译质量，完全符合翻译任务需求

在我的测试环境中，具体为NVIDIA GeForce RTX 4060笔记本版本，观察到IQ3_S(1500)相较于IQ4_XS(1500)在翻译速度上实现了接近三倍的提升(分别为30tokens/s和12tokens/s)，而两者之间的翻译性能差异较小

然而，目前最新发布的Sakura-14B-Qwen2beta版本，包括v0.9及预览版v0.10pre0，均未内置支持IQ3_S量化的模型格式。在尝试自主进行模型量化过程中，因不明原因导致模型无法正常运行

所以请求官方支持一下IQ3_S量化模型或者提供fp16模型

**Comment by pipixia244** [comment]
是否考虑到大部分人系统有一定占用，且占用大小不一？

**Comment by CberYellowstone** [comment]
7.7太极限了，稍微波动一下就OOM了

**Comment by lingyezhixing** [comment]
> 是否考虑到大部分人系统有一定占用，且占用大小不一？

再次精细测试发现1500的上下文并不能完全利用，因为模型量化后性能降低，长文本会导致行数不匹配的概率上升，最佳翻译长度缩减为270左右，所以只需要配置650左右的上下文即可，此时占用为7.2GB左右，在轻小说翻译机器人上可以正常翻译。

如果选择IQ3_XS那么显存占用会进一步下降到7GB以下

想把14B压缩进8G的显存里同时还想保留较高的翻译质量，不可能再降低精度和占用了。
