### ISSUE TITLE
[Feature Request] 添加工具`RPGMakerMV-Translator-SakuraLLM`

### ISSUE THREAD

**Issue by thiliapr** [SakuraLLM/Sakura-13B-Galgame#81]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [RPGMaker_LLaMA_Translator](https://github.com/fkiliver/RPGMaker_LLaMA_Translator)要搭配[MTOOL](https://afdian.net/a/AdventCirno)使用，不够开源（自由）。

**Describe the solution you'd like**
在`已经接入模型的工具`添加[RPGMakerMV-Translator-SakuraLLM](https://github.com/thiliapr/RPGMakerMV-Translator-SakuraLLM)，并添加备注`无需MTool`以与[RPGMaker_LLaMA_Translator](https://github.com/fkiliver/RPGMaker_LLaMA_Translator)区别。

**Describe alternatives you've considered**
将就一下，用MTool。

**Additional context**
啥都没有。

**Comment by yujianke100** [comment]
用了一下，这个工具是直接找data文件夹下不需要解包的json做翻译了吧。MTOOL除了各类功能，还支持非常多的引擎。加上直接修改游戏源文件的风险也是要考虑的，现在这个项目我觉得还不能被视作是一个好的替代。
